### ISSUE TITLE
Explanation for Lucene branch

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/hnswrecall#7]
It's unclear why there is a Lucene branch required for this benchmark.  The branch will be out of date and also means the benchmark isn't against standard Lucene.

**Comment by jbellis** [comment]
https://github.com/jbellis/hnswrecall/commit/5521207cc71976c8e0a2178b6dbefe9a666fceee

**Comment by rickjamesthe6th** [comment]
The Lucene concurrent branch is 8 months out of date.

**Comment by jbellis** [comment]
PRs accepted.

**Comment by rickjamesthe6th** [comment]
Lucene has concurrent building now.

**Comment by jbellis** [comment]
Cool, feel free to submit a PR to use mainline lucene.
