### ISSUE TITLE
https://github.com/erikbern/ann-benchmarks does not contain hdf5 files

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/hnswrecall#8]
https://github.com/erikbern/ann-benchmarks seems to be an actual benchmark, the hdf5 files are not present.  Direct links to the hdf5 files would be helpful.  

The files listed in `Bench` are:

`var files = List.of(
                "hdf5/nytimes-256-angular.hdf5",
                "hdf5/glove-100-angular.hdf5",
                "hdf5/glove-200-angular.hdf5",
                "hdf5/sift-128-euclidean.hdf5");`

**Comment by rickjamesthe6th** [comment]
A gurgle search locates them at:

https://huggingface.co/datasets/hhy3/ann-datasets/tree/main

Are these the correct ones?

**Comment by rickjamesthe6th** [comment]
sift-128-euclidean.hdf5 is no longer available.  https://github.com/erikbern/ann-benchmarks/blob/main/README.md hasn't been updated in 1 year

**Comment by rickjamesthe6th** [comment]
None of the files linked from https://github.com/erikbern/ann-benchmarks/blob/main/README.md  actually work

**Comment by jbellis** [comment]
I just tried the first one http://ann-benchmarks.com/deep-image-96-angular.hdf5 and it worked fine

**Comment by rickjamesthe6th** [comment]
Chrome isn't liking the insecure download, clicking on the link does nothing.  `Save link as` is required, then passing this screen:

<img width="322" alt="Screenshot 2024-04-15 at 6 49 03 PM" src="https://github.com/jbellis/hnswrecall/assets/166993754/27d494db-1a91-4fa5-86ec-10cd0fadf4d4">
